version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
    commit-message:
      prefix: ⬆
    labels:
      - "dependencies"
    groups:
      github-actions:
        patterns:
          - "*"
  # Python uv
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
    commit-message:
      prefix: ⬆
    labels: [dependencies]
    groups:
      python-packages:
        patterns:
          - "*"
  # bun
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
    commit-message:
      prefix: ⬆
    labels: [dependencies]
    ignore:
      - dependency-name: "@hey-api/openapi-ts"
      - dependency-name: "@tanstack/react-table"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "typescript"
        update-types:
          - "version-update:semver-major"
    groups:
      npm-packages:
        patterns:
          - "*"
  # Docker
  - package-ecosystem: docker
    directories:
      - /backend
      - /frontend
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
    commit-message:
      prefix: ⬆
    groups:
      docker:
        patterns:
          - "*"
  # Docker Compose
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
    commit-message:
      prefix: ⬆
    groups:
      docker-compose:
        patterns:
          - "*"
