Add academic status to students table

Revision ID: b0e1d2c3f4a5
Revises: fe56fa70289e
Create Date: 2026-09-19 23:20:02.867

""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0e1d2c3f4a5'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students',
        sa.Column('academic_status', postgresql.ENUM('regular', 'irregular', name='academicstatus', create_type=False),
            nullable=True
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'academic_status')
    # ### end Alembic commands ###

