Add academic status to students table

Revision ID: b0e1d2c3f4a5
Revises: fe56fa70289e
Create Date: 2026-09-19 23:26:04.015

""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0e1d2c3f4a5'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None

# Define the enum type with create_type=True so it gets created in PostgreSQL
academic_status_enum = postgresql.ENUM('regular', 'irregular', name='academicstatus', create_type=True)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First create the enum type in PostgreSQL
    academic_status_enum.create(op.get_bind(), checkfirst=True)
    
    # Then add the column using the same enum instance
    op.add_column('students',
        sa.Column('academic_status', academic_status_enum,
            nullable=True
        )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'academic_status')
    
    # Drop the enum type from PostgreSQL
    academic_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

