"""add student event attendance models

Revision ID: bdb851e7e407
Revises: fe56fa70289e
Create Date: 2026-09-11 02:00:03.686401

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bdb851e7e407'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('event_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('event_date', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('start_time', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('end_time', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('attendance_mode', sa.Enum('time_in_only', 'time_in_time_out', name='attendancemode'), nullable=False),
    sa.Column('organizer', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sa.Enum('draft', 'open', 'closed', name='eventstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('student_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('extension', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('year', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('section', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nfc_uid', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('nfc_registered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_nfc_uid'), 'student', ['nfc_uid'], unique=True)
    op.create_index(op.f('ix_student_student_number'), 'student', ['student_number'], unique=True)
    op.create_table('attendance',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('time_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('present', 'time_in_only', 'completed', 'incomplete', name='attendancestatus'), nullable=False),
    sa.Column('scan_method', sa.Enum('nfc', 'manual', name='scanmethod'), nullable=False),
    sa.Column('scanned_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['scanned_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'student_id', name='uq_attendance_event_student')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    op.drop_index(op.f('ix_student_student_number'), table_name='student')
    op.drop_index(op.f('ix_student_nfc_uid'), table_name='student')
    op.drop_table('student')
    op.drop_table('event')
    # ### end Alembic commands ###
