/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as GetMyQrRouteImport } from './routes/get-my-qr'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAccountRouteImport } from './routes/_layout/account'
import { Route as LayoutAdministrationRouteImport } from './routes/_layout/administration'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutDeveloperRouteImport } from './routes/_layout/developer'
import { Route as LayoutEventsRouteImport } from './routes/_layout/events'
import { Route as LayoutRecordsRouteImport } from './routes/_layout/records'
import { Route as LayoutScannerRouteImport } from './routes/_layout/scanner'
import { Route as LayoutSectionsRouteImport } from './routes/_layout/sections'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutAccountIndexRouteImport } from './routes/_layout/account/index'
import { Route as LayoutAccountProfileRouteImport } from './routes/_layout/account/profile'
import { Route as LayoutAccountSecurityRouteImport } from './routes/_layout/account/security'
import { Route as LayoutAdministrationIndexRouteImport } from './routes/_layout/administration/index'
import { Route as LayoutAdministrationAttendanceRouteImport } from './routes/_layout/administration/attendance'
import { Route as LayoutAdministrationAuditLogsRouteImport } from './routes/_layout/administration/audit-logs'
import { Route as LayoutAdministrationClassRepresentativesRouteImport } from './routes/_layout/administration/class-representatives'
import { Route as LayoutAdministrationRolesRouteImport } from './routes/_layout/administration/roles'
import { Route as LayoutAdministrationScannerPermissionsRouteImport } from './routes/_layout/administration/scanner-permissions'
import { Route as LayoutAdministrationUsersRouteImport } from './routes/_layout/administration/users'
import { Route as LayoutEventsEventIdRouteImport } from './routes/_layout/events/$eventId'
import { Route as LayoutRecordsExportRouteImport } from './routes/_layout/records/export'
import { Route as LayoutRecordsHistoryRouteImport } from './routes/_layout/records/history'
import { Route as LayoutRecordsIncompleteRouteImport } from './routes/_layout/records/incomplete'
import { Route as LayoutScannerEventRouteImport } from './routes/_layout/scanner/event'
import { Route as LayoutScannerManualRouteImport } from './routes/_layout/scanner/manual'
import { Route as LayoutScannerNfcRouteImport } from './routes/_layout/scanner/nfc'
import { Route as LayoutScannerSyncRouteImport } from './routes/_layout/scanner/sync'
import { Route as LayoutScannerTimeInRouteImport } from './routes/_layout/scanner/time-in'
import { Route as LayoutScannerTimeOutRouteImport } from './routes/_layout/scanner/time-out'
import { Route as LayoutSectionsSectionIdRouteImport } from './routes/_layout/sections/$sectionId'
import { Route as LayoutSettingsIndexRouteImport } from './routes/_layout/settings/index'
import { Route as LayoutSettingsAttendanceRulesRouteImport } from './routes/_layout/settings/attendance-rules'
import { Route as LayoutSettingsOrganizationRouteImport } from './routes/_layout/settings/organization'
import { Route as LayoutSettingsTimeOutRouteImport } from './routes/_layout/settings/time-out'
import { Route as LayoutEventsEventIdRegistrationRouteImport } from './routes/_layout/events/$eventId/registration'
import { Route as LayoutEventsEventIdRosterRouteImport } from './routes/_layout/events/$eventId/roster'
import { Route as LayoutEventsEventIdSessionsRouteImport } from './routes/_layout/events/$eventId/sessions'
import { Route as LayoutSectionsSectionIdStudentsRouteImport } from './routes/_layout/sections/$sectionId/students'
import { Route as LayoutSectionsSectionIdStudentsStudentIdRouteImport } from './routes/_layout/sections/$sectionId/students/$studentId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const GetMyQrRoute = GetMyQrRouteImport.update({
  id: '/get-my-qr',
  path: '/get-my-qr',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAccountRoute = LayoutAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdministrationRoute = LayoutAdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDeveloperRoute = LayoutDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsRoute = LayoutEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRecordsRoute = LayoutRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutScannerRoute = LayoutScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSectionsRoute = LayoutSectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAccountIndexRoute = LayoutAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutAccountRoute,
} as any)
const LayoutAccountProfileRoute = LayoutAccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutAccountRoute,
} as any)
const LayoutAccountSecurityRoute = LayoutAccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => LayoutAccountRoute,
} as any)
const LayoutAdministrationIndexRoute =
  LayoutAdministrationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAdministrationRoute,
  } as any)
const LayoutAdministrationAttendanceRoute =
  LayoutAdministrationAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => LayoutAdministrationRoute,
  } as any)
const LayoutAdministrationAuditLogsRoute =
  LayoutAdministrationAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => LayoutAdministrationRoute,
  } as any)
const LayoutAdministrationClassRepresentativesRoute =
  LayoutAdministrationClassRepresentativesRouteImport.update({
    id: '/class-representatives',
    path: '/class-representatives',
    getParentRoute: () => LayoutAdministrationRoute,
  } as any)
const LayoutAdministrationRolesRoute =
  LayoutAdministrationRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => LayoutAdministrationRoute,
  } as any)
const LayoutAdministrationScannerPermissionsRoute =
  LayoutAdministrationScannerPermissionsRouteImport.update({
    id: '/scanner-permissions',
    path: '/scanner-permissions',
    getParentRoute: () => LayoutAdministrationRoute,
  } as any)
const LayoutAdministrationUsersRoute =
  LayoutAdministrationUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => LayoutAdministrationRoute,
  } as any)
const LayoutEventsEventIdRoute = LayoutEventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => LayoutEventsRoute,
} as any)
const LayoutRecordsExportRoute = LayoutRecordsExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => LayoutRecordsRoute,
} as any)
const LayoutRecordsHistoryRoute = LayoutRecordsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => LayoutRecordsRoute,
} as any)
const LayoutRecordsIncompleteRoute = LayoutRecordsIncompleteRouteImport.update({
  id: '/incomplete',
  path: '/incomplete',
  getParentRoute: () => LayoutRecordsRoute,
} as any)
const LayoutScannerEventRoute = LayoutScannerEventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => LayoutScannerRoute,
} as any)
const LayoutScannerManualRoute = LayoutScannerManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => LayoutScannerRoute,
} as any)
const LayoutScannerNfcRoute = LayoutScannerNfcRouteImport.update({
  id: '/nfc',
  path: '/nfc',
  getParentRoute: () => LayoutScannerRoute,
} as any)
const LayoutScannerSyncRoute = LayoutScannerSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => LayoutScannerRoute,
} as any)
const LayoutScannerTimeInRoute = LayoutScannerTimeInRouteImport.update({
  id: '/time-in',
  path: '/time-in',
  getParentRoute: () => LayoutScannerRoute,
} as any)
const LayoutScannerTimeOutRoute = LayoutScannerTimeOutRouteImport.update({
  id: '/time-out',
  path: '/time-out',
  getParentRoute: () => LayoutScannerRoute,
} as any)
const LayoutSectionsSectionIdRoute = LayoutSectionsSectionIdRouteImport.update({
  id: '/$sectionId',
  path: '/$sectionId',
  getParentRoute: () => LayoutSectionsRoute,
} as any)
const LayoutSettingsIndexRoute = LayoutSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutSettingsRoute,
} as any)
const LayoutSettingsAttendanceRulesRoute =
  LayoutSettingsAttendanceRulesRouteImport.update({
    id: '/attendance-rules',
    path: '/attendance-rules',
    getParentRoute: () => LayoutSettingsRoute,
  } as any)
const LayoutSettingsOrganizationRoute =
  LayoutSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => LayoutSettingsRoute,
  } as any)
const LayoutSettingsTimeOutRoute = LayoutSettingsTimeOutRouteImport.update({
  id: '/time-out',
  path: '/time-out',
  getParentRoute: () => LayoutSettingsRoute,
} as any)
const LayoutEventsEventIdRegistrationRoute =
  LayoutEventsEventIdRegistrationRouteImport.update({
    id: '/registration',
    path: '/registration',
    getParentRoute: () => LayoutEventsEventIdRoute,
  } as any)
const LayoutEventsEventIdRosterRoute =
  LayoutEventsEventIdRosterRouteImport.update({
    id: '/roster',
    path: '/roster',
    getParentRoute: () => LayoutEventsEventIdRoute,
  } as any)
const LayoutEventsEventIdSessionsRoute =
  LayoutEventsEventIdSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => LayoutEventsEventIdRoute,
  } as any)
const LayoutSectionsSectionIdStudentsRoute =
  LayoutSectionsSectionIdStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => LayoutSectionsSectionIdRoute,
  } as any)
const LayoutSectionsSectionIdStudentsStudentIdRoute =
  LayoutSectionsSectionIdStudentsStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => LayoutSectionsSectionIdStudentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/get-my-qr': typeof GetMyQrRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/account': typeof LayoutAccountRouteWithChildren
  '/administration': typeof LayoutAdministrationRouteWithChildren
  '/dashboard': typeof LayoutDashboardRoute
  '/developer': typeof LayoutDeveloperRoute
  '/events': typeof LayoutEventsRouteWithChildren
  '/records': typeof LayoutRecordsRouteWithChildren
  '/scanner': typeof LayoutScannerRouteWithChildren
  '/sections': typeof LayoutSectionsRouteWithChildren
  '/settings': typeof LayoutSettingsRouteWithChildren
  '/account/profile': typeof LayoutAccountProfileRoute
  '/account/security': typeof LayoutAccountSecurityRoute
  '/administration/attendance': typeof LayoutAdministrationAttendanceRoute
  '/administration/audit-logs': typeof LayoutAdministrationAuditLogsRoute
  '/administration/class-representatives': typeof LayoutAdministrationClassRepresentativesRoute
  '/administration/roles': typeof LayoutAdministrationRolesRoute
  '/administration/scanner-permissions': typeof LayoutAdministrationScannerPermissionsRoute
  '/administration/users': typeof LayoutAdministrationUsersRoute
  '/events/$eventId': typeof LayoutEventsEventIdRouteWithChildren
  '/records/export': typeof LayoutRecordsExportRoute
  '/records/history': typeof LayoutRecordsHistoryRoute
  '/records/incomplete': typeof LayoutRecordsIncompleteRoute
  '/scanner/event': typeof LayoutScannerEventRoute
  '/scanner/manual': typeof LayoutScannerManualRoute
  '/scanner/nfc': typeof LayoutScannerNfcRoute
  '/scanner/sync': typeof LayoutScannerSyncRoute
  '/scanner/time-in': typeof LayoutScannerTimeInRoute
  '/scanner/time-out': typeof LayoutScannerTimeOutRoute
  '/sections/$sectionId': typeof LayoutSectionsSectionIdRouteWithChildren
  '/settings/attendance-rules': typeof LayoutSettingsAttendanceRulesRoute
  '/settings/organization': typeof LayoutSettingsOrganizationRoute
  '/settings/time-out': typeof LayoutSettingsTimeOutRoute
  '/account/': typeof LayoutAccountIndexRoute
  '/administration/': typeof LayoutAdministrationIndexRoute
  '/settings/': typeof LayoutSettingsIndexRoute
  '/events/$eventId/registration': typeof LayoutEventsEventIdRegistrationRoute
  '/events/$eventId/roster': typeof LayoutEventsEventIdRosterRoute
  '/events/$eventId/sessions': typeof LayoutEventsEventIdSessionsRoute
  '/sections/$sectionId/students': typeof LayoutSectionsSectionIdStudentsRouteWithChildren
  '/sections/$sectionId/students/$studentId': typeof LayoutSectionsSectionIdStudentsStudentIdRoute
}
export interface FileRoutesByTo {
  '/get-my-qr': typeof GetMyQrRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/developer': typeof LayoutDeveloperRoute
  '/events': typeof LayoutEventsRouteWithChildren
  '/records': typeof LayoutRecordsRouteWithChildren
  '/scanner': typeof LayoutScannerRouteWithChildren
  '/sections': typeof LayoutSectionsRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/account/profile': typeof LayoutAccountProfileRoute
  '/account/security': typeof LayoutAccountSecurityRoute
  '/administration/attendance': typeof LayoutAdministrationAttendanceRoute
  '/administration/audit-logs': typeof LayoutAdministrationAuditLogsRoute
  '/administration/class-representatives': typeof LayoutAdministrationClassRepresentativesRoute
  '/administration/roles': typeof LayoutAdministrationRolesRoute
  '/administration/scanner-permissions': typeof LayoutAdministrationScannerPermissionsRoute
  '/administration/users': typeof LayoutAdministrationUsersRoute
  '/events/$eventId': typeof LayoutEventsEventIdRouteWithChildren
  '/records/export': typeof LayoutRecordsExportRoute
  '/records/history': typeof LayoutRecordsHistoryRoute
  '/records/incomplete': typeof LayoutRecordsIncompleteRoute
  '/scanner/event': typeof LayoutScannerEventRoute
  '/scanner/manual': typeof LayoutScannerManualRoute
  '/scanner/nfc': typeof LayoutScannerNfcRoute
  '/scanner/sync': typeof LayoutScannerSyncRoute
  '/scanner/time-in': typeof LayoutScannerTimeInRoute
  '/scanner/time-out': typeof LayoutScannerTimeOutRoute
  '/sections/$sectionId': typeof LayoutSectionsSectionIdRouteWithChildren
  '/settings/attendance-rules': typeof LayoutSettingsAttendanceRulesRoute
  '/settings/organization': typeof LayoutSettingsOrganizationRoute
  '/settings/time-out': typeof LayoutSettingsTimeOutRoute
  '/account': typeof LayoutAccountIndexRoute
  '/administration': typeof LayoutAdministrationIndexRoute
  '/settings': typeof LayoutSettingsIndexRoute
  '/events/$eventId/registration': typeof LayoutEventsEventIdRegistrationRoute
  '/events/$eventId/roster': typeof LayoutEventsEventIdRosterRoute
  '/events/$eventId/sessions': typeof LayoutEventsEventIdSessionsRoute
  '/sections/$sectionId/students': typeof LayoutSectionsSectionIdStudentsRouteWithChildren
  '/sections/$sectionId/students/$studentId': typeof LayoutSectionsSectionIdStudentsStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/get-my-qr': typeof GetMyQrRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/account': typeof LayoutAccountRouteWithChildren
  '/_layout/administration': typeof LayoutAdministrationRouteWithChildren
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/developer': typeof LayoutDeveloperRoute
  '/_layout/events': typeof LayoutEventsRouteWithChildren
  '/_layout/records': typeof LayoutRecordsRouteWithChildren
  '/_layout/scanner': typeof LayoutScannerRouteWithChildren
  '/_layout/sections': typeof LayoutSectionsRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/account/profile': typeof LayoutAccountProfileRoute
  '/_layout/account/security': typeof LayoutAccountSecurityRoute
  '/_layout/administration/attendance': typeof LayoutAdministrationAttendanceRoute
  '/_layout/administration/audit-logs': typeof LayoutAdministrationAuditLogsRoute
  '/_layout/administration/class-representatives': typeof LayoutAdministrationClassRepresentativesRoute
  '/_layout/administration/roles': typeof LayoutAdministrationRolesRoute
  '/_layout/administration/scanner-permissions': typeof LayoutAdministrationScannerPermissionsRoute
  '/_layout/administration/users': typeof LayoutAdministrationUsersRoute
  '/_layout/events/$eventId': typeof LayoutEventsEventIdRouteWithChildren
  '/_layout/records/export': typeof LayoutRecordsExportRoute
  '/_layout/records/history': typeof LayoutRecordsHistoryRoute
  '/_layout/records/incomplete': typeof LayoutRecordsIncompleteRoute
  '/_layout/scanner/event': typeof LayoutScannerEventRoute
  '/_layout/scanner/manual': typeof LayoutScannerManualRoute
  '/_layout/scanner/nfc': typeof LayoutScannerNfcRoute
  '/_layout/scanner/sync': typeof LayoutScannerSyncRoute
  '/_layout/scanner/time-in': typeof LayoutScannerTimeInRoute
  '/_layout/scanner/time-out': typeof LayoutScannerTimeOutRoute
  '/_layout/sections/$sectionId': typeof LayoutSectionsSectionIdRouteWithChildren
  '/_layout/settings/attendance-rules': typeof LayoutSettingsAttendanceRulesRoute
  '/_layout/settings/organization': typeof LayoutSettingsOrganizationRoute
  '/_layout/settings/time-out': typeof LayoutSettingsTimeOutRoute
  '/_layout/account/': typeof LayoutAccountIndexRoute
  '/_layout/administration/': typeof LayoutAdministrationIndexRoute
  '/_layout/settings/': typeof LayoutSettingsIndexRoute
  '/_layout/events/$eventId/registration': typeof LayoutEventsEventIdRegistrationRoute
  '/_layout/events/$eventId/roster': typeof LayoutEventsEventIdRosterRoute
  '/_layout/events/$eventId/sessions': typeof LayoutEventsEventIdSessionsRoute
  '/_layout/sections/$sectionId/students': typeof LayoutSectionsSectionIdStudentsRouteWithChildren
  '/_layout/sections/$sectionId/students/$studentId': typeof LayoutSectionsSectionIdStudentsStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/get-my-qr'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/account'
    | '/administration'
    | '/dashboard'
    | '/developer'
    | '/events'
    | '/records'
    | '/scanner'
    | '/sections'
    | '/settings'
    | '/account/profile'
    | '/account/security'
    | '/administration/attendance'
    | '/administration/audit-logs'
    | '/administration/class-representatives'
    | '/administration/roles'
    | '/administration/scanner-permissions'
    | '/administration/users'
    | '/events/$eventId'
    | '/records/export'
    | '/records/history'
    | '/records/incomplete'
    | '/scanner/event'
    | '/scanner/manual'
    | '/scanner/nfc'
    | '/scanner/sync'
    | '/scanner/time-in'
    | '/scanner/time-out'
    | '/sections/$sectionId'
    | '/settings/attendance-rules'
    | '/settings/organization'
    | '/settings/time-out'
    | '/account/'
    | '/administration/'
    | '/settings/'
    | '/events/$eventId/registration'
    | '/events/$eventId/roster'
    | '/events/$eventId/sessions'
    | '/sections/$sectionId/students'
    | '/sections/$sectionId/students/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/get-my-qr'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/developer'
    | '/events'
    | '/records'
    | '/scanner'
    | '/sections'
    | '/'
    | '/account/profile'
    | '/account/security'
    | '/administration/attendance'
    | '/administration/audit-logs'
    | '/administration/class-representatives'
    | '/administration/roles'
    | '/administration/scanner-permissions'
    | '/administration/users'
    | '/events/$eventId'
    | '/records/export'
    | '/records/history'
    | '/records/incomplete'
    | '/scanner/event'
    | '/scanner/manual'
    | '/scanner/nfc'
    | '/scanner/sync'
    | '/scanner/time-in'
    | '/scanner/time-out'
    | '/sections/$sectionId'
    | '/settings/attendance-rules'
    | '/settings/organization'
    | '/settings/time-out'
    | '/account'
    | '/administration'
    | '/settings'
    | '/events/$eventId/registration'
    | '/events/$eventId/roster'
    | '/events/$eventId/sessions'
    | '/sections/$sectionId/students'
    | '/sections/$sectionId/students/$studentId'
  id:
    | '__root__'
    | '/_layout'
    | '/get-my-qr'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/account'
    | '/_layout/administration'
    | '/_layout/dashboard'
    | '/_layout/developer'
    | '/_layout/events'
    | '/_layout/records'
    | '/_layout/scanner'
    | '/_layout/sections'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/account/profile'
    | '/_layout/account/security'
    | '/_layout/administration/attendance'
    | '/_layout/administration/audit-logs'
    | '/_layout/administration/class-representatives'
    | '/_layout/administration/roles'
    | '/_layout/administration/scanner-permissions'
    | '/_layout/administration/users'
    | '/_layout/events/$eventId'
    | '/_layout/records/export'
    | '/_layout/records/history'
    | '/_layout/records/incomplete'
    | '/_layout/scanner/event'
    | '/_layout/scanner/manual'
    | '/_layout/scanner/nfc'
    | '/_layout/scanner/sync'
    | '/_layout/scanner/time-in'
    | '/_layout/scanner/time-out'
    | '/_layout/sections/$sectionId'
    | '/_layout/settings/attendance-rules'
    | '/_layout/settings/organization'
    | '/_layout/settings/time-out'
    | '/_layout/account/'
    | '/_layout/administration/'
    | '/_layout/settings/'
    | '/_layout/events/$eventId/registration'
    | '/_layout/events/$eventId/roster'
    | '/_layout/events/$eventId/sessions'
    | '/_layout/sections/$sectionId/students'
    | '/_layout/sections/$sectionId/students/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  GetMyQrRoute: typeof GetMyQrRoute
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-my-qr': {
      id: '/get-my-qr'
      path: '/get-my-qr'
      fullPath: '/get-my-qr'
      preLoaderRoute: typeof GetMyQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/account': {
      id: '/_layout/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof LayoutAccountRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/administration': {
      id: '/_layout/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof LayoutAdministrationRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/developer': {
      id: '/_layout/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof LayoutDeveloperRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events': {
      id: '/_layout/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof LayoutEventsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/records': {
      id: '/_layout/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof LayoutRecordsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/scanner': {
      id: '/_layout/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof LayoutScannerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sections': {
      id: '/_layout/sections'
      path: '/sections'
      fullPath: '/sections'
      preLoaderRoute: typeof LayoutSectionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/account/': {
      id: '/_layout/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof LayoutAccountIndexRouteImport
      parentRoute: typeof LayoutAccountRoute
    }
    '/_layout/account/profile': {
      id: '/_layout/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof LayoutAccountProfileRouteImport
      parentRoute: typeof LayoutAccountRoute
    }
    '/_layout/account/security': {
      id: '/_layout/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof LayoutAccountSecurityRouteImport
      parentRoute: typeof LayoutAccountRoute
    }
    '/_layout/administration/': {
      id: '/_layout/administration/'
      path: '/'
      fullPath: '/administration/'
      preLoaderRoute: typeof LayoutAdministrationIndexRouteImport
      parentRoute: typeof LayoutAdministrationRoute
    }
    '/_layout/administration/attendance': {
      id: '/_layout/administration/attendance'
      path: '/attendance'
      fullPath: '/administration/attendance'
      preLoaderRoute: typeof LayoutAdministrationAttendanceRouteImport
      parentRoute: typeof LayoutAdministrationRoute
    }
    '/_layout/administration/audit-logs': {
      id: '/_layout/administration/audit-logs'
      path: '/audit-logs'
      fullPath: '/administration/audit-logs'
      preLoaderRoute: typeof LayoutAdministrationAuditLogsRouteImport
      parentRoute: typeof LayoutAdministrationRoute
    }
    '/_layout/administration/class-representatives': {
      id: '/_layout/administration/class-representatives'
      path: '/class-representatives'
      fullPath: '/administration/class-representatives'
      preLoaderRoute: typeof LayoutAdministrationClassRepresentativesRouteImport
      parentRoute: typeof LayoutAdministrationRoute
    }
    '/_layout/administration/roles': {
      id: '/_layout/administration/roles'
      path: '/roles'
      fullPath: '/administration/roles'
      preLoaderRoute: typeof LayoutAdministrationRolesRouteImport
      parentRoute: typeof LayoutAdministrationRoute
    }
    '/_layout/administration/scanner-permissions': {
      id: '/_layout/administration/scanner-permissions'
      path: '/scanner-permissions'
      fullPath: '/administration/scanner-permissions'
      preLoaderRoute: typeof LayoutAdministrationScannerPermissionsRouteImport
      parentRoute: typeof LayoutAdministrationRoute
    }
    '/_layout/administration/users': {
      id: '/_layout/administration/users'
      path: '/users'
      fullPath: '/administration/users'
      preLoaderRoute: typeof LayoutAdministrationUsersRouteImport
      parentRoute: typeof LayoutAdministrationRoute
    }
    '/_layout/events/$eventId': {
      id: '/_layout/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof LayoutEventsEventIdRouteImport
      parentRoute: typeof LayoutEventsRoute
    }
    '/_layout/records/export': {
      id: '/_layout/records/export'
      path: '/export'
      fullPath: '/records/export'
      preLoaderRoute: typeof LayoutRecordsExportRouteImport
      parentRoute: typeof LayoutRecordsRoute
    }
    '/_layout/records/history': {
      id: '/_layout/records/history'
      path: '/history'
      fullPath: '/records/history'
      preLoaderRoute: typeof LayoutRecordsHistoryRouteImport
      parentRoute: typeof LayoutRecordsRoute
    }
    '/_layout/records/incomplete': {
      id: '/_layout/records/incomplete'
      path: '/incomplete'
      fullPath: '/records/incomplete'
      preLoaderRoute: typeof LayoutRecordsIncompleteRouteImport
      parentRoute: typeof LayoutRecordsRoute
    }
    '/_layout/scanner/event': {
      id: '/_layout/scanner/event'
      path: '/event'
      fullPath: '/scanner/event'
      preLoaderRoute: typeof LayoutScannerEventRouteImport
      parentRoute: typeof LayoutScannerRoute
    }
    '/_layout/scanner/manual': {
      id: '/_layout/scanner/manual'
      path: '/manual'
      fullPath: '/scanner/manual'
      preLoaderRoute: typeof LayoutScannerManualRouteImport
      parentRoute: typeof LayoutScannerRoute
    }
    '/_layout/scanner/nfc': {
      id: '/_layout/scanner/nfc'
      path: '/nfc'
      fullPath: '/scanner/nfc'
      preLoaderRoute: typeof LayoutScannerNfcRouteImport
      parentRoute: typeof LayoutScannerRoute
    }
    '/_layout/scanner/sync': {
      id: '/_layout/scanner/sync'
      path: '/sync'
      fullPath: '/scanner/sync'
      preLoaderRoute: typeof LayoutScannerSyncRouteImport
      parentRoute: typeof LayoutScannerRoute
    }
    '/_layout/scanner/time-in': {
      id: '/_layout/scanner/time-in'
      path: '/time-in'
      fullPath: '/scanner/time-in'
      preLoaderRoute: typeof LayoutScannerTimeInRouteImport
      parentRoute: typeof LayoutScannerRoute
    }
    '/_layout/scanner/time-out': {
      id: '/_layout/scanner/time-out'
      path: '/time-out'
      fullPath: '/scanner/time-out'
      preLoaderRoute: typeof LayoutScannerTimeOutRouteImport
      parentRoute: typeof LayoutScannerRoute
    }
    '/_layout/sections/$sectionId': {
      id: '/_layout/sections/$sectionId'
      path: '/$sectionId'
      fullPath: '/sections/$sectionId'
      preLoaderRoute: typeof LayoutSectionsSectionIdRouteImport
      parentRoute: typeof LayoutSectionsRoute
    }
    '/_layout/settings/': {
      id: '/_layout/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof LayoutSettingsIndexRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/attendance-rules': {
      id: '/_layout/settings/attendance-rules'
      path: '/attendance-rules'
      fullPath: '/settings/attendance-rules'
      preLoaderRoute: typeof LayoutSettingsAttendanceRulesRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/organization': {
      id: '/_layout/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof LayoutSettingsOrganizationRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/time-out': {
      id: '/_layout/settings/time-out'
      path: '/time-out'
      fullPath: '/settings/time-out'
      preLoaderRoute: typeof LayoutSettingsTimeOutRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/events/$eventId/registration': {
      id: '/_layout/events/$eventId/registration'
      path: '/registration'
      fullPath: '/events/$eventId/registration'
      preLoaderRoute: typeof LayoutEventsEventIdRegistrationRouteImport
      parentRoute: typeof LayoutEventsEventIdRoute
    }
    '/_layout/events/$eventId/roster': {
      id: '/_layout/events/$eventId/roster'
      path: '/roster'
      fullPath: '/events/$eventId/roster'
      preLoaderRoute: typeof LayoutEventsEventIdRosterRouteImport
      parentRoute: typeof LayoutEventsEventIdRoute
    }
    '/_layout/events/$eventId/sessions': {
      id: '/_layout/events/$eventId/sessions'
      path: '/sessions'
      fullPath: '/events/$eventId/sessions'
      preLoaderRoute: typeof LayoutEventsEventIdSessionsRouteImport
      parentRoute: typeof LayoutEventsEventIdRoute
    }
    '/_layout/sections/$sectionId/students': {
      id: '/_layout/sections/$sectionId/students'
      path: '/students'
      fullPath: '/sections/$sectionId/students'
      preLoaderRoute: typeof LayoutSectionsSectionIdStudentsRouteImport
      parentRoute: typeof LayoutSectionsSectionIdRoute
    }
    '/_layout/sections/$sectionId/students/$studentId': {
      id: '/_layout/sections/$sectionId/students/$studentId'
      path: '/$studentId'
      fullPath: '/sections/$sectionId/students/$studentId'
      preLoaderRoute: typeof LayoutSectionsSectionIdStudentsStudentIdRouteImport
      parentRoute: typeof LayoutSectionsSectionIdStudentsRoute
    }
  }
}

interface LayoutAccountRouteChildren {
  LayoutAccountProfileRoute: typeof LayoutAccountProfileRoute
  LayoutAccountSecurityRoute: typeof LayoutAccountSecurityRoute
  LayoutAccountIndexRoute: typeof LayoutAccountIndexRoute
}

const LayoutAccountRouteChildren: LayoutAccountRouteChildren = {
  LayoutAccountProfileRoute: LayoutAccountProfileRoute,
  LayoutAccountSecurityRoute: LayoutAccountSecurityRoute,
  LayoutAccountIndexRoute: LayoutAccountIndexRoute,
}

const LayoutAccountRouteWithChildren = LayoutAccountRoute._addFileChildren(
  LayoutAccountRouteChildren,
)

interface LayoutAdministrationRouteChildren {
  LayoutAdministrationAttendanceRoute: typeof LayoutAdministrationAttendanceRoute
  LayoutAdministrationAuditLogsRoute: typeof LayoutAdministrationAuditLogsRoute
  LayoutAdministrationClassRepresentativesRoute: typeof LayoutAdministrationClassRepresentativesRoute
  LayoutAdministrationRolesRoute: typeof LayoutAdministrationRolesRoute
  LayoutAdministrationScannerPermissionsRoute: typeof LayoutAdministrationScannerPermissionsRoute
  LayoutAdministrationUsersRoute: typeof LayoutAdministrationUsersRoute
  LayoutAdministrationIndexRoute: typeof LayoutAdministrationIndexRoute
}

const LayoutAdministrationRouteChildren: LayoutAdministrationRouteChildren = {
  LayoutAdministrationAttendanceRoute: LayoutAdministrationAttendanceRoute,
  LayoutAdministrationAuditLogsRoute: LayoutAdministrationAuditLogsRoute,
  LayoutAdministrationClassRepresentativesRoute:
    LayoutAdministrationClassRepresentativesRoute,
  LayoutAdministrationRolesRoute: LayoutAdministrationRolesRoute,
  LayoutAdministrationScannerPermissionsRoute:
    LayoutAdministrationScannerPermissionsRoute,
  LayoutAdministrationUsersRoute: LayoutAdministrationUsersRoute,
  LayoutAdministrationIndexRoute: LayoutAdministrationIndexRoute,
}

const LayoutAdministrationRouteWithChildren =
  LayoutAdministrationRoute._addFileChildren(LayoutAdministrationRouteChildren)

interface LayoutEventsEventIdRouteChildren {
  LayoutEventsEventIdRegistrationRoute: typeof LayoutEventsEventIdRegistrationRoute
  LayoutEventsEventIdRosterRoute: typeof LayoutEventsEventIdRosterRoute
  LayoutEventsEventIdSessionsRoute: typeof LayoutEventsEventIdSessionsRoute
}

const LayoutEventsEventIdRouteChildren: LayoutEventsEventIdRouteChildren = {
  LayoutEventsEventIdRegistrationRoute: LayoutEventsEventIdRegistrationRoute,
  LayoutEventsEventIdRosterRoute: LayoutEventsEventIdRosterRoute,
  LayoutEventsEventIdSessionsRoute: LayoutEventsEventIdSessionsRoute,
}

const LayoutEventsEventIdRouteWithChildren =
  LayoutEventsEventIdRoute._addFileChildren(LayoutEventsEventIdRouteChildren)

interface LayoutEventsRouteChildren {
  LayoutEventsEventIdRoute: typeof LayoutEventsEventIdRouteWithChildren
}

const LayoutEventsRouteChildren: LayoutEventsRouteChildren = {
  LayoutEventsEventIdRoute: LayoutEventsEventIdRouteWithChildren,
}

const LayoutEventsRouteWithChildren = LayoutEventsRoute._addFileChildren(
  LayoutEventsRouteChildren,
)

interface LayoutRecordsRouteChildren {
  LayoutRecordsExportRoute: typeof LayoutRecordsExportRoute
  LayoutRecordsHistoryRoute: typeof LayoutRecordsHistoryRoute
  LayoutRecordsIncompleteRoute: typeof LayoutRecordsIncompleteRoute
}

const LayoutRecordsRouteChildren: LayoutRecordsRouteChildren = {
  LayoutRecordsExportRoute: LayoutRecordsExportRoute,
  LayoutRecordsHistoryRoute: LayoutRecordsHistoryRoute,
  LayoutRecordsIncompleteRoute: LayoutRecordsIncompleteRoute,
}

const LayoutRecordsRouteWithChildren = LayoutRecordsRoute._addFileChildren(
  LayoutRecordsRouteChildren,
)

interface LayoutScannerRouteChildren {
  LayoutScannerEventRoute: typeof LayoutScannerEventRoute
  LayoutScannerManualRoute: typeof LayoutScannerManualRoute
  LayoutScannerNfcRoute: typeof LayoutScannerNfcRoute
  LayoutScannerSyncRoute: typeof LayoutScannerSyncRoute
  LayoutScannerTimeInRoute: typeof LayoutScannerTimeInRoute
  LayoutScannerTimeOutRoute: typeof LayoutScannerTimeOutRoute
}

const LayoutScannerRouteChildren: LayoutScannerRouteChildren = {
  LayoutScannerEventRoute: LayoutScannerEventRoute,
  LayoutScannerManualRoute: LayoutScannerManualRoute,
  LayoutScannerNfcRoute: LayoutScannerNfcRoute,
  LayoutScannerSyncRoute: LayoutScannerSyncRoute,
  LayoutScannerTimeInRoute: LayoutScannerTimeInRoute,
  LayoutScannerTimeOutRoute: LayoutScannerTimeOutRoute,
}

const LayoutScannerRouteWithChildren = LayoutScannerRoute._addFileChildren(
  LayoutScannerRouteChildren,
)

interface LayoutSectionsSectionIdStudentsRouteChildren {
  LayoutSectionsSectionIdStudentsStudentIdRoute: typeof LayoutSectionsSectionIdStudentsStudentIdRoute
}

const LayoutSectionsSectionIdStudentsRouteChildren: LayoutSectionsSectionIdStudentsRouteChildren =
  {
    LayoutSectionsSectionIdStudentsStudentIdRoute:
      LayoutSectionsSectionIdStudentsStudentIdRoute,
  }

const LayoutSectionsSectionIdStudentsRouteWithChildren =
  LayoutSectionsSectionIdStudentsRoute._addFileChildren(
    LayoutSectionsSectionIdStudentsRouteChildren,
  )

interface LayoutSectionsSectionIdRouteChildren {
  LayoutSectionsSectionIdStudentsRoute: typeof LayoutSectionsSectionIdStudentsRouteWithChildren
}

const LayoutSectionsSectionIdRouteChildren: LayoutSectionsSectionIdRouteChildren =
  {
    LayoutSectionsSectionIdStudentsRoute:
      LayoutSectionsSectionIdStudentsRouteWithChildren,
  }

const LayoutSectionsSectionIdRouteWithChildren =
  LayoutSectionsSectionIdRoute._addFileChildren(
    LayoutSectionsSectionIdRouteChildren,
  )

interface LayoutSectionsRouteChildren {
  LayoutSectionsSectionIdRoute: typeof LayoutSectionsSectionIdRouteWithChildren
}

const LayoutSectionsRouteChildren: LayoutSectionsRouteChildren = {
  LayoutSectionsSectionIdRoute: LayoutSectionsSectionIdRouteWithChildren,
}

const LayoutSectionsRouteWithChildren = LayoutSectionsRoute._addFileChildren(
  LayoutSectionsRouteChildren,
)

interface LayoutSettingsRouteChildren {
  LayoutSettingsAttendanceRulesRoute: typeof LayoutSettingsAttendanceRulesRoute
  LayoutSettingsOrganizationRoute: typeof LayoutSettingsOrganizationRoute
  LayoutSettingsTimeOutRoute: typeof LayoutSettingsTimeOutRoute
  LayoutSettingsIndexRoute: typeof LayoutSettingsIndexRoute
}

const LayoutSettingsRouteChildren: LayoutSettingsRouteChildren = {
  LayoutSettingsAttendanceRulesRoute: LayoutSettingsAttendanceRulesRoute,
  LayoutSettingsOrganizationRoute: LayoutSettingsOrganizationRoute,
  LayoutSettingsTimeOutRoute: LayoutSettingsTimeOutRoute,
  LayoutSettingsIndexRoute: LayoutSettingsIndexRoute,
}

const LayoutSettingsRouteWithChildren = LayoutSettingsRoute._addFileChildren(
  LayoutSettingsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAccountRoute: typeof LayoutAccountRouteWithChildren
  LayoutAdministrationRoute: typeof LayoutAdministrationRouteWithChildren
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutDeveloperRoute: typeof LayoutDeveloperRoute
  LayoutEventsRoute: typeof LayoutEventsRouteWithChildren
  LayoutRecordsRoute: typeof LayoutRecordsRouteWithChildren
  LayoutScannerRoute: typeof LayoutScannerRouteWithChildren
  LayoutSectionsRoute: typeof LayoutSectionsRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAccountRoute: LayoutAccountRouteWithChildren,
  LayoutAdministrationRoute: LayoutAdministrationRouteWithChildren,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutDeveloperRoute: LayoutDeveloperRoute,
  LayoutEventsRoute: LayoutEventsRouteWithChildren,
  LayoutRecordsRoute: LayoutRecordsRouteWithChildren,
  LayoutScannerRoute: LayoutScannerRouteWithChildren,
  LayoutSectionsRoute: LayoutSectionsRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  GetMyQrRoute: GetMyQrRoute,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
