/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is automatically generated by TanStack Router.
// It is kept in sync here so the committed route tree matches the Phase 1 reconstruction routes.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutEventsRouteImport } from './routes/_layout/events'
import { Route as LayoutRecordsRouteImport } from './routes/_layout/records'
import { Route as LayoutScannerRouteImport } from './routes/_layout/scanner'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutStudentsRouteImport } from './routes/_layout/students'
import { Route as LayoutSectionsRouteImport } from './routes/_layout/sections'
import { Route as LayoutSectionsSectionIdRouteImport } from './routes/_layout/sections/$sectionId'
import { Route as LayoutAccountRouteImport } from './routes/_layout/account'

const LayoutRoute = LayoutRouteImport.update({ id: '/_layout', getParentRoute: () => rootRouteImport } as any)
const LoginRoute = LoginRouteImport.update({ id: '/login', path: '/login', getParentRoute: () => rootRouteImport } as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({ id: '/recover-password', path: '/recover-password', getParentRoute: () => rootRouteImport } as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({ id: '/reset-password', path: '/reset-password', getParentRoute: () => rootRouteImport } as any)
const SignupRoute = SignupRouteImport.update({ id: '/signup', path: '/signup', getParentRoute: () => rootRouteImport } as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => LayoutRoute } as any)
const LayoutAccountRoute = LayoutAccountRouteImport.update({ id: '/account', path: '/account', getParentRoute: () => LayoutRoute } as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({ id: '/admin', path: '/admin', getParentRoute: () => LayoutRoute } as any)
const LayoutEventsRoute = LayoutEventsRouteImport.update({ id: '/events', path: '/events', getParentRoute: () => LayoutRoute } as any)
const LayoutRecordsRoute = LayoutRecordsRouteImport.update({ id: '/records', path: '/records', getParentRoute: () => LayoutRoute } as any)
const LayoutScannerRoute = LayoutScannerRouteImport.update({ id: '/scanner', path: '/scanner', getParentRoute: () => LayoutRoute } as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({ id: '/settings', path: '/settings', getParentRoute: () => LayoutRoute } as any)
const LayoutStudentsRoute = LayoutStudentsRouteImport.update({ id: '/students', path: '/students', getParentRoute: () => LayoutRoute } as any)
const LayoutSectionsRoute = LayoutSectionsRouteImport.update({ id: '/sections', path: '/sections', getParentRoute: () => LayoutRoute } as any)
const LayoutSectionsSectionIdRoute = LayoutSectionsSectionIdRouteImport.update({ id: '/sections/$sectionId', path: '/sections/$sectionId', getParentRoute: () => LayoutRoute } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/account': typeof LayoutAccountRoute
  '/admin': typeof LayoutAdminRoute
  '/events': typeof LayoutEventsRoute
  '/records': typeof LayoutRecordsRoute
  '/scanner': typeof LayoutScannerRoute
  '/settings': typeof LayoutSettingsRoute
  '/students': typeof LayoutStudentsRoute
  '/sections': typeof LayoutSectionsRoute
  '/sections/$sectionId': typeof LayoutSectionsSectionIdRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/account': typeof LayoutAccountRoute
  '/admin': typeof LayoutAdminRoute
  '/events': typeof LayoutEventsRoute
  '/records': typeof LayoutRecordsRoute
  '/scanner': typeof LayoutScannerRoute
  '/settings': typeof LayoutSettingsRoute
  '/students': typeof LayoutStudentsRoute
  '/sections': typeof LayoutSectionsRoute
  '/sections/$sectionId': typeof LayoutSectionsSectionIdRoute
  '/': typeof LayoutIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/account': typeof LayoutAccountRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/events': typeof LayoutEventsRoute
  '/_layout/records': typeof LayoutRecordsRoute
  '/_layout/scanner': typeof LayoutScannerRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/students': typeof LayoutStudentsRoute
  '/_layout/sections': typeof LayoutSectionsRoute
  '/_layout/sections/$sectionId': typeof LayoutSectionsSectionIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: keyof FileRoutesByFullPath
  fileRoutesByTo: FileRoutesByTo
  to: keyof FileRoutesByTo
  id: keyof FileRoutesById
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': { id: '/_layout'; path: ''; fullPath: '/'; preLoaderRoute: typeof LayoutRouteImport; parentRoute: typeof rootRouteImport }
    '/login': { id: '/login'; path: '/login'; fullPath: '/login'; preLoaderRoute: typeof LoginRouteImport; parentRoute: typeof rootRouteImport }
    '/recover-password': { id: '/recover-password'; path: '/recover-password'; fullPath: '/recover-password'; preLoaderRoute: typeof RecoverPasswordRouteImport; parentRoute: typeof rootRouteImport }
    '/reset-password': { id: '/reset-password'; path: '/reset-password'; fullPath: '/reset-password'; preLoaderRoute: typeof ResetPasswordRouteImport; parentRoute: typeof rootRouteImport }
    '/signup': { id: '/signup'; path: '/signup'; fullPath: '/signup'; preLoaderRoute: typeof SignupRouteImport; parentRoute: typeof rootRouteImport }
    '/_layout/': { id: '/_layout/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof LayoutIndexRouteImport; parentRoute: typeof LayoutRoute }
    '/_layout/account': { id: '/_layout/account'; path: '/account'; fullPath: '/account'; preLoaderRoute: typeof LayoutAccountRouteImport; parentRoute: typeof LayoutRoute }
    '/_layout/admin': { id: '/_layout/admin'; path: '/admin'; fullPath: '/admin'; preLoaderRoute: typeof LayoutAdminRouteImport; parentRoute: typeof LayoutRoute }
    '/_layout/events': { id: '/_layout/events'; path: '/events'; fullPath: '/events'; preLoaderRoute: typeof LayoutEventsRouteImport; parentRoute: typeof LayoutRoute }
    '/_layout/records': { id: '/_layout/records'; path: '/records'; fullPath: '/records'; preLoaderRoute: typeof LayoutRecordsRouteImport; parentRoute: typeof LayoutRoute }
    '/_layout/scanner': { id: '/_layout/scanner'; path: '/scanner'; fullPath: '/scanner'; preLoaderRoute: typeof LayoutScannerRouteImport; parentRoute: typeof LayoutRoute }
    '/_layout/settings': { id: '/_layout/settings'; path: '/settings'; fullPath: '/settings'; preLoaderRoute: typeof LayoutSettingsRouteImport; parentRoute: typeof LayoutRoute }
    '/_layout/students': { id: '/_layout/students'; path: '/students'; fullPath: '/students'; preLoaderRoute: typeof LayoutStudentsRouteImport; parentRoute: typeof LayoutRoute }
    '/_layout/sections': { id: '/_layout/sections'; path: '/sections'; fullPath: '/sections'; preLoaderRoute: typeof LayoutSectionsRouteImport; parentRoute: typeof LayoutRoute }
    '/_layout/sections/$sectionId': { id: '/_layout/sections/$sectionId'; path: '/sections/$sectionId'; fullPath: '/sections/$sectionId'; preLoaderRoute: typeof LayoutSectionsSectionIdRouteImport; parentRoute: typeof LayoutRoute }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAccountRoute: typeof LayoutAccountRoute
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutEventsRoute: typeof LayoutEventsRoute
  LayoutRecordsRoute: typeof LayoutRecordsRoute
  LayoutScannerRoute: typeof LayoutScannerRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutStudentsRoute: typeof LayoutStudentsRoute
  LayoutSectionsRoute: typeof LayoutSectionsRoute
  LayoutSectionsSectionIdRoute: typeof LayoutSectionsSectionIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute,
  LayoutAccountRoute,
  LayoutAdminRoute,
  LayoutEventsRoute,
  LayoutRecordsRoute,
  LayoutScannerRoute,
  LayoutSettingsRoute,
  LayoutStudentsRoute,
  LayoutSectionsRoute,
  LayoutSectionsSectionIdRoute,
}

const LayoutRouteWithChildren = LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SignupRoute,
}

export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
