import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { useState } from "react"
import { UsersService, type UserPublic, type UserRole } from "@/client"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"

const roles: UserRole[] = ["developer", "super_admin", "admin", "class_representative", "student"]
export function UsersAdministrationPage() {
  const qc = useQueryClient(); const [q, setQ] = useState("")
  const query = useQuery({ queryKey: ["admin-users"], queryFn: () => UsersService.readUsers({ query: { skip: 0, limit: 1000 } }) })
  const mutation = useMutation({ mutationFn: ({ id, body }: { id: string; body: Parameters<typeof UsersService.updateUser>[0]["body"] }) => UsersService.updateUser({ path: { user_id: id }, body }), onSuccess: () => qc.invalidateQueries({ queryKey: ["admin-users"] }) })
  const users = (query.data?.data.data ?? []).filter((u: UserPublic) => `${u.full_name ?? ""} ${u.email}`.toLowerCase().includes(q.toLowerCase()))
  return <div className="space-y-6"><div><h1 className="text-2xl font-semibold">User Accounts</h1><p className="mt-1 text-sm text-muted-foreground">Manage existing application accounts using the existing user API.</p></div><Input placeholder="Search users…" value={q} onChange={e => setQ(e.target.value)} />{query.isError && <Card><CardContent className="py-8 text-center text-sm text-destructive">Unable to load users.</CardContent></Card>}<Card><CardHeader><CardTitle className="text-base">Accounts</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Name</th><th className="p-3">Email</th><th className="p-3">Role</th><th className="p-3">Active</th><th className="p-3">Scanner</th><th className="p-3">Action</th></tr></thead><tbody>{users.map((u: UserPublic) => <UserRow key={u.id} user={u} onSave={(body) => mutation.mutate({ id: u.id, body })} saving={mutation.isPending} />)}</tbody></table>{!query.isLoading && users.length === 0 && <p className="py-8 text-center text-sm text-muted-foreground">No users found.</p>}</CardContent></Card></div>
}
function UserRow({ user, onSave, saving }: { user: UserPublic; onSave: (body: Parameters<typeof UsersService.updateUser>[0]["body"]) => void; saving: boolean }) { const [role, setRole] = useState<UserRole>(user.role ?? "student"); const [active, setActive] = useState(Boolean(user.is_active)); const [scan, setScan] = useState(Boolean(user.can_scan)); return <tr className="border-b"><td className="p-3 font-medium">{user.full_name || "—"}</td><td className="p-3">{user.email}</td><td className="p-3"><Select value={role} onValueChange={(v) => setRole(v as UserRole)}><SelectTrigger className="w-[190px]"><SelectValue /></SelectTrigger><SelectContent>{roles.map(r => <SelectItem key={r} value={r}>{r.replace(/_/g, " ")}</SelectItem>)}</SelectContent></Select></td><td className="p-3"><Button size="sm" variant={active ? "default" : "outline"} onClick={() => setActive(!active)}>{active ? "Active" : "Inactive"}</Button></td><td className="p-3"><Button size="sm" variant={scan ? "default" : "outline"} onClick={() => setScan(!scan)}>{scan ? "Allowed" : "Denied"}</Button></td><td className="p-3"><Button size="sm" onClick={() => onSave({ role, is_active: active, can_scan: scan })} disabled={saving}>Save</Button></td></tr> }
